# Generated by Django 4.2.5 on 2023-12-10 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0006_remove_userprofile_followers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='followers', to='userprofile.userprofile'),
        ),
    ]
