# Generated by Django 4.2.5 on 2023-12-10 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0007_alter_userprofile_following'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='following',
            new_name='followings',
        ),
    ]
